
import { Navbar } from "@/components/Navbar/Navbar";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { Footer } from "@/components/Footer/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="container-scroller">
          {/* Navbar start */}
          <Navbar />
          {/* Navbar ends */}
          <div className="container-fluid page-body-wrapper">
            {/* sidebar start */}
            <Sidebar />
            {/* sidebar end */}
            <div className="main-panel">
              {children}
              {/* footer start */}
              <Footer />
              {/* footer end */}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
